logo: /assets/img/logo.jpg
title: Wansatilab
description: A Associação Moçambicana - Mulheres na Tecnologia
domain: wansati.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://wansati.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /   # place folder name if the site is served in a subfolder
show_downloads: true
google_analytics:

# Social media links
# (This can be commented out if not required.)
social:
  facebook: "#"
  twitter: "#"
  google: "#"
  instagram: "#"
  pinterest: "#"
  snapchat: "#"
  linkedin: "in/#"

# Build settings
markdown: kramdown